[package]
name = "solana-hello-world"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.18.26"
bumpalo = "3.12.0"
arrayref = "0.3.6"
thiserror = "1.0"

[lib]
name = "solana_hello_world"
crate-type = ["cdylib", "lib"] 